### ISSUE TITLE
AttributeError: module 'black' has no attribute 'find_pyproject_toml'

### ISSUE THREAD

**Issue by jvacek** [MarkusH/django-migrations-formatter#18]
Admittedly, we're pinned to a slightly older version of `black` (`black==19.10b0`), would be nice if this were backwards compat. I suppose we're not the only one pinned until v22 comes out

Full TB:
```
Traceback (most recent call last):
  File "/path/./manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/path/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/path/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/path/venv/lib/python3.9/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/path/venv/lib/python3.9/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/path/venv/lib/python3.9/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/path/venv/lib/python3.9/site-packages/django/core/management/commands/makemigrations.py", line 182, in handle
    self.write_migration_files(changes)
  File "/path/venv/lib/python3.9/site-packages/django/core/management/commands/makemigrations.py", line 220, in write_migration_files
    migration_string = writer.as_string()
  File "/path/venv/lib/python3.9/site-packages/django_migrations_formatter/__init__.py", line 44, in as_string
    content = self._format_black(content)
  File "/path/venv/lib/python3.9/site-packages/django_migrations_formatter/__init__.py", line 19, in format_black
    config_file = black.find_pyproject_toml((self.basedir,))
AttributeError: module 'black' has no attribute 'find_pyproject_toml'
```

**Comment by MarkusH** [comment]
Do you want to open a pull request for this? I don't have the bandwidth to make the change myself. I'm happy to make a release afterwards
