### ISSUE TITLE
TypeError calling `black`

### ISSUE THREAD

**Issue by nbhargava** [MarkusH/django-migrations-formatter#29]
There seems to be a compatibility issue `black` 22.3.0 (which is current).

```
Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/makemigrations.py", line 214, in handle
    self.write_migration_files(changes)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/makemigrations.py", line 255, in write_migration_files
    migration_string = writer.as_string()
  File "/usr/local/lib/python3.9/site-packages/django_migrations_formatter/__init__.py", line 44, in as_string
    content = self._format_black(content)
  File "/usr/local/lib/python3.9/site-packages/django_migrations_formatter/__init__.py", line 25, in format_black
    mode = black.Mode(
  File "<string>", line 3, in __init__
TypeError: set object expected; got list
```

This issue seems to be related: https://github.com/psf/black/issues/2829

**Comment by nbhargava** [comment]
I was on an old version of this library!
